[package]
name = "raytracer"
version = "0.1.0"
edition = "2021"

[lib]
#crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = "fat"
codegen-units = 1

[dependencies]
image = "0.24.4"
rayon = "1.5.3"
